/*
 * This file was generated by generate-schemas tool.
 * DO NOT EDIT MANUALLY!!!
 */
import { Type, TSchema } from "@sinclair/typebox";

export const CalendarInstanceSchema = Type.Object({
  id: Type.String(),
  calendar: Type.String(),
  description: Type.String(),
  type: Type.Literal("HA"),
  grade: Type.String(),
});

export const PageQueryDtoSchema = Type.Object({
  from: Type.Optional(
    Type.Number({ default: 0, minimum: 0, description: "Номер страницы" })
  ),
  pageSize: Type.Optional(
    Type.Number({
      default: 20,
      minimum: 1,
      maximum: 200,
      description: "Размер страницы",
    })
  ),
});

export const PageDtoSchema = <T extends TSchema>(T: T) =>
  Type.Object({
    pages: Type.Array(T, {
      description: "Список элементов (данных) на текущей странице",
    }),
    total: Type.Number({
      minimum: 0,
      description:
        "Общее количество элементов во всей выборке (на всех страницах)",
    }),
  });

export const GeminiInlineDataSchema = Type.Object({
  mimeType: Type.String(),
  data: Type.String(),
});

export const GeminiFileDataSchema = Type.Object({
  mimeType: Type.String(),
  fileUri: Type.String(),
});

export const GeminiFunctionCallSchema = Type.Object({
  name: Type.String(),
  args: Type.Record(Type.String(), Type.Unknown()),
});

export const GeminiFunctionResponseSchema = Type.Object({
  name: Type.String(),
  response: Type.Record(Type.String(), Type.Unknown()),
});

export const GeminiPartSchema = Type.Object({
  text: Type.Optional(Type.String()),
  inlineData: Type.Optional(GeminiInlineDataSchema),
  fileData: Type.Optional(GeminiFileDataSchema),
  functionCall: Type.Optional(GeminiFunctionCallSchema),
  functionResponse: Type.Optional(GeminiFunctionResponseSchema),
  thoughtSignature: Type.Optional(Type.String()),
});

export const GeminiContentSchema = Type.Object({
  parts: Type.Array(GeminiPartSchema),
  role: Type.Union([
    Type.Literal("user"),
    Type.Literal("model"),
    Type.String(),
  ]),
});

export const GeminiFinishReasonSchema = Type.Union([
  Type.Literal("FINISH_REASON_UNSPECIFIED"),
  Type.Literal("STOP"),
  Type.Literal("MAX_TOKENS"),
  Type.Literal("SAFETY"),
  Type.Literal("RECITATION"),
  Type.Literal("LANGUAGE"),
  Type.Literal("OTHER"),
  Type.Literal("BLOCKLIST"),
  Type.Literal("PROHIBITED_CONTENT"),
  Type.Literal("SPII"),
  Type.Literal("MALFORMED_FUNCTION_CALL"),
  Type.Literal("IMAGE_SAFETY"),
]);

export const GeminiSafetyRatingSchema = Type.Object({
  category: Type.String(),
  probability: Type.String(),
  blocked: Type.Optional(Type.Boolean()),
});

export const GeminiCitationMetadataSchema = Type.Object({
  citationSources: Type.Array(
    Type.Object({
      startIndex: Type.Optional(Type.Number()),
      endIndex: Type.Optional(Type.Number()),
      uri: Type.Optional(Type.String()),
      license: Type.Optional(Type.String()),
    })
  ),
});

export const GeminiCandidateSchema = Type.Object({
  content: GeminiContentSchema,
  finishReason: Type.Optional(GeminiFinishReasonSchema),
  index: Type.Optional(Type.Number()),
  safetyRatings: Type.Optional(Type.Array(GeminiSafetyRatingSchema)),
  citationMetadata: Type.Optional(GeminiCitationMetadataSchema),
  tokenCount: Type.Optional(Type.Number()),
});

export const GeminiModalityTokenCountSchema = Type.Object({
  modality: Type.Union([
    Type.Literal("TEXT"),
    Type.Literal("IMAGE"),
    Type.Literal("VIDEO"),
    Type.Literal("AUDIO"),
    Type.Literal("DOCUMENT"),
    Type.String(),
  ]),
  tokenCount: Type.Number(),
});

export const GeminiUsageMetadataSchema = Type.Object({
  promptTokenCount: Type.Optional(Type.Number()),
  candidatesTokenCount: Type.Optional(Type.Number()),
  totalTokenCount: Type.Optional(Type.Number()),
  thoughtsTokenCount: Type.Optional(Type.Number()),
  cachedContentTokenCount: Type.Optional(Type.Number()),
  promptTokensDetails: Type.Optional(
    Type.Array(GeminiModalityTokenCountSchema)
  ),
  candidatesTokensDetails: Type.Optional(
    Type.Array(GeminiModalityTokenCountSchema)
  ),
  serviceTier: Type.Optional(
    Type.Union([
      Type.Literal("standard"),
      Type.Literal("flex"),
      Type.Literal("priority"),
      Type.String(),
    ])
  ),
});

export const GeminiPromptFeedbackSchema = Type.Object({
  blockReason: Type.Optional(Type.String()),
  safetyRatings: Type.Optional(Type.Array(GeminiSafetyRatingSchema)),
  blockReasonMessage: Type.Optional(Type.String()),
});

export const GeminiErrorDetailSchema = Type.Object(
  {
    "@type": Type.String(),
  },
  {
    additionalProperties: Type.Unknown(),
  }
);

export const GeminiErrorSchema = Type.Object({
  code: Type.Number(),
  message: Type.String(),
  status: Type.String(),
  details: Type.Optional(Type.Array(GeminiErrorDetailSchema)),
});

export const GeminiResponseSchema = Type.Object({
  candidates: Type.Optional(Type.Array(GeminiCandidateSchema)),
  usageMetadata: Type.Optional(GeminiUsageMetadataSchema),
  modelVersion: Type.Optional(Type.String()),
  responseId: Type.Optional(Type.String()),
  promptFeedback: Type.Optional(GeminiPromptFeedbackSchema),
  error: Type.Optional(GeminiErrorSchema),
});

export const JobDtoSchema = Type.Object({
  id: Type.String(),
  fileName: Type.String(),
  type: Type.Union([
    Type.Literal("check"),
    Type.Literal("parse"),
    Type.Literal("schedule"),
    Type.Literal("upload"),
  ]),
  status: Type.Union([
    Type.Literal("new"),
    Type.Literal("processing"),
    Type.Literal("pending"),
    Type.Literal("done"),
    Type.Literal("error"),
  ]),
  error: Type.Optional(Type.String()),
  startAt: Type.Number(),
  finishedAt: Type.Optional(Type.Number()),
});

export const CheckJobDtoSchema = Type.Composite([
  JobDtoSchema,
  Type.Object({
    metrics: Type.Optional(Type.Record(Type.String(), Type.Number())),
  }),
]);

export const ParseJobDtoSchema = Type.Composite([
  JobDtoSchema,
  Type.Object({
    model: Type.Optional(Type.String()),
    parseAttempt: Type.Number(),
    response: Type.Optional(Type.String()),
  }),
]);

export const CalendarEventDtoSchema = Type.Object({
  summary: Type.String({ example: "Математика" }),
  start_date_time: Type.String({ example: "2026-09-29T08:30:00" }),
  end_date_time: Type.String({ example: "2026-09-29T09:10:00" }),
  location: Type.Optional(Type.String({ example: 0.991304347826087 })),
  description: Type.Optional(Type.String({ example: "Урок: Математика" })),
});

export const ClassScheduleDtoSchema = Type.Object({
  grade: Type.String({ example: "5А" }),
  events: Type.Array(CalendarEventDtoSchema),
});

export const ParsedScheduleDtoSchema = Type.Object({
  date: Type.String({ example: 1988 }),
  classes: Type.Array(ClassScheduleDtoSchema),
});

export const ScheduleJobDtoSchema = Type.Composite([
  JobDtoSchema,
  Type.Object({
    date: Type.Number(),
    classes: Type.Array(ClassScheduleDtoSchema),
  }),
]);

export const CalendarJobDtoSchema = Type.Composite([
  JobDtoSchema,
  Type.Object({
    date: Type.Number(),
    calendar: CalendarInstanceSchema,
    events: Type.Array(CalendarEventDtoSchema),
  }),
]);
