import { parseArgs } from 'node:util';
import { TypeScriptToTypeBox } from '@sinclair/typebox-codegen';
import * as fs from 'fs';
import * as path from 'path';

const banner = " * This file was generated by generate-schemas tool.\n * DO NOT EDIT MANUALLY!!!";

function generate(inputPath, outputPath) {
  if (!fs.existsSync(inputPath)) {
    console.error(`Ошибка: Входной файл не найден по пути ${inputPath}.`);
    process.exit(1);
  }

  const tsCode = fs.readFileSync(inputPath, 'utf-8');

  let typeBoxCode = TypeScriptToTypeBox.Generate(tsCode, {
    useTypeBoxImport: false
  });

  const dtoTypeRegexp = /export type \w+[ <].*\n/g;
  const dtoNameRegex = /export const (\w+) =/g;
  const dtoNames = [];
  let match;

  // Чистим типы
  typeBoxCode = typeBoxCode.replace(dtoTypeRegexp, '');

  // Собираем имена
  while ((match = dtoNameRegex.exec(typeBoxCode)) !== null) {
    dtoNames.push(match[1]);
  }

  // Добавляем суффикс Schema ко всем именам
  dtoNames.forEach((dtoName) => {
    const nameRegex = new RegExp(`\\b${dtoName}\\b`, 'g');

    typeBoxCode = typeBoxCode.replace(nameRegex, `${dtoName}Schema`);
  });

  typeBoxCode = `/*\n${banner}\n*/\nimport { Type, TSchema } from '@sinclair/typebox';\n\n${typeBoxCode.trim()}`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, typeBoxCode, 'utf-8');

  console.log(`🎉 Схемы TypeBox успешно сгенерированы и переименованы в ${outputPath}`);
}

const { values } = parseArgs({
  options: {
    input:  { type: 'string', short: 'i' },
    output: { type: 'string', short: 'o' },
  },
});

if (!values.input || !values.output) {
  console.error('Usage: generate-schemas -i <input.d.ts> -o <output.ts>');
  process.exit(1);
}
generate(values.input, values.output);
